### ISSUE TITLE
logo制作

### ISSUE THREAD

**Issue by Earlystarry** [hust-open-atom-club/TranslateProject#10]
为我们的HCTT制作logo，要求体现HCTT的特色，可以加入一些Linux内核的元素。

**Comment by mudongliang** [comment]
@gitveg 现在天一把俱乐部的logo重新设计了，可以在他的设计基础上整一个HCTT的logo

**Comment by mudongliang** [comment]
尽量和俱乐部的logo保持统一

**Comment by mudongliang** [comment]
俱乐部 Logo 和其他设计资源现已开放
- 提供 PNG 与 SVG 两种格式，若要进行修改，推荐使用 Figma 进行编辑
- 可以使用 GitHub 提供的外链进行访问，但请注意其尺寸并未针对 Icon 展示进行优化
- 仓库链接：​[GitHub - hust-open-atom-club/logos: Logos for HUST OpenAtom Open Source Club](https://github.com/hust-open-atom-club/logos)

**Comment by mudongliang** [comment]
![img_v3_029n_c75a2299-96f5-471d-9634-5ef94010f64g](https://github.com/hust-open-atom-club/TranslateProject/assets/6214861/fa0c3b69-6b1d-469d-a59d-f5023f648942)

这是我们目前新鲜出炉的 v1。
