### ISSUE TITLE
其他问题

### ISSUE THREAD

**Issue by Earlystarry** [hust-open-atom-club/TranslateProject#12]
1. 关于已发布的文章，微信公众号可能存在链接被和谐等问题，仿照 “linux中国” 的模式，应该提供一个【查看原文】的按钮，并导航到原文页面。
 例如：[https://linux.cn/share/](https://gitee.com/link?target=https%3A%2F%2Flinux.cn%2Fshare%2F)
 应该集成在该repo的page中，还是新搭建一个站点？
 
2. Github pages目前可能国内连通性存在问题，下面是程子丘简单测试的结果

   ![image](https://github.com/hust-open-atom-club/TranslateProject/assets/144318232/a57e3eb8-2322-46cd-99b2-5f365ba5f665)

**Comment by mudongliang** [comment]
1. 查看原文这个事情，预计加入我们的wiki中
2. 目前这个连通性问题不大
