### ISSUE TITLE
LLVM Doc?

### ISSUE THREAD

**Issue by tttturtle-russ** [hust-open-atom-club/TranslateProject#149]
AFAIK llvm doc has no Chinese translation, we can be the first one. I've raised an [issue](https://github.com/llvm/llvm-project/issues/101809) about this in llvm-project repo.

**Comment by tttturtle-russ** [comment]
https://github.com/llvm/llvm-project/tree/main/llvm/docs

**Comment by mudongliang** [comment]
Are you sure llvm has no Chinese translation?

**Comment by tttturtle-russ** [comment]
Most of them are too old to be read. The newest version of LLVM is 18.1.8, but the latest and complete translation stays LLVM 12. Many APIs or traits have changed dramatically.

**Comment by mudongliang** [comment]
Maybe we can translate some parts, e.g., sanitizer parts at the beginning

**Comment by tttturtle-russ** [comment]
Sure. I just begin to learn llvm IR and plan to translate some documents into Chinese.

**Comment by mudongliang** [comment]
You can try to collect some articles to see if anyone in the HCTT SIG is interested in the translation
