### ISSUE TITLE
文末“返回开头”点击无效

### ISSUE THREAD

**Issue by mudongliang** [hust-open-atom-club/TranslateProject#20]

**Comment by JingJing1016** [comment]
这个问题好像只在edge上有？
如果从HCTT主页点进post，然后滑到最下方，按钮是无效的，同时上方也不会显示进度条。
如果刷新当前的post界面，或者直接访问某个post，不从主页点进去，就是一切正常的。

**Comment by jxlpzqc** [comment]
已解决，关闭该issue。
