### ISSUE TITLE
页面增加 “贡献者榜单”

### ISSUE THREAD

**Issue by Earlystarry** [hust-open-atom-club/TranslateProject#6]
1. 更改导言区规范，translator改成下面的格式
 [username](https://github.com/mudongliang)
 
2. 统计所有贡献者榜单并排名。

| 用户名 | 选题 | 翻译 | 校对 | 发布 |
| ---- | ---- | ------ | --- | --- |
| mudongliang | XXX | XXX | XXX | XXX |

3. 通过 [https://api.github.com/search/users?q=user@example.com](https://gitee.com/link?target=https%3A%2F%2Fapi.github.com%2Fsearch%2Fusers%3Fq%3Duser%40example.com) 找到用户头像，并制作“贡献值榜单页面”，页头的导航栏可以导航到该榜单。

**Comment by shandianchengzi** [comment]
> 1. 更改导言区规范，translator改成下面的格式
>    [username](https://github.com/mudongliang)
> 2. 统计所有贡献者榜单并排名。
> 
> 用户名	选题	翻译	校对	发布
> mudongliang	XXX	XXX	XXX	XXX
> 3. 通过 [https://api.github.com/search/users?q=user@example.com](https://gitee.com/link?target=https%3A%2F%2Fapi.github.com%2Fsearch%2Fusers%3Fq%3Duser%40example.com) 找到用户头像，并制作“贡献值榜单页面”，页头的导航栏可以导航到该榜单。

考虑做成每个种类一个榜单，而不是单人榜单？

目前这个表格形式不知道是按总数算排名、还是按每项加权来算排名

**Comment by mudongliang** [comment]
你的意思是每个阶段给一个榜单吗？这个我同意，可以按照现在用的这种分类（翻译王者，校验大佬之类的）来列。

<img width="510" alt="截屏2024-04-05 21 37 07" src="https://github.com/hust-open-atom-club/TranslateProject/assets/6214861/c5f8fd50-722f-40fb-bc5b-a6c415a3486f">
