### ISSUE TITLE
检查在启用 CI 前原有文章的 metadata 有效性

### ISSUE THREAD

**Issue by inscripoem** [hust-open-atom-club/TranslateProject#60]
- 为保证检查全面，可以在 #59 解决后进行
- 包含 CI 目前的检查内容，由于没有 PR 被触发，可以将对 PR 操作者的检查改为验证每一阶段操作者的 id 是否为有效的 Github Username

**Comment by mudongliang** [comment]
如果有这个功能，我们就可以随便在文件末尾添加空白行等做法来检查所有文件

**Comment by inscripoem** [comment]
> 如果有这个功能，我们就可以随便在文件末尾添加空白行等做法来检查所有文件

我想到一个新思路，对于所有文件的操作可以通过重新建立一个可手动触发的仓库全量检查工作流来进行，每次触发就对整个仓库的文章进行检查。这样不需要去手动修改大量文件，也能应对直接push到master branch而没有经过CI的意外情况
