### ISSUE TITLE
一些细节更改

### ISSUE THREAD

**Issue by Earlystarry** [hust-open-atom-club/TranslateProject#7]
1. 页面的列表按时间倒序排序

2. 文章页面显示更多元数据：例如翻译时间，译者，收集者，文章类型等信息。
  文章页面例子： [https://hctt.hust.college/posts/general/20240223-linux-is-a-cna/](https://gitee.com/link?target=https%3A%2F%2Fhctt.hust.college%2Fposts%2Fgeneral%2F20240223-linux-is-a-cna%2F)

**Comment by mudongliang** [comment]
文章按照文件夹还有一个默认的元数据属性，就是category: general/syzkaller/kernel。

**Comment by mudongliang** [comment]
> 文章按照文件夹还有一个默认的元数据属性，就是category: general/syzkaller/kernel。

Done by adding different icons to mark its type.
