### ISSUE TITLE
Markdown 版本要在最后显示添加来源链接

### ISSUE THREAD

**Issue by Earlystarry** [hust-open-atom-club/TranslateProject#8]

**Comment by mudongliang** [comment]
对于所有的文章，最后自动化地添加如下所示内容：

> 译自：http://www.kroah.com/log/blog/2024/02/13/linux-is-a-cna/
>
> 译者：[sun-yu-777](https://gitee.com/sun-yu-777) 校对：[mudongliang](https://gitee.com/mudongliang)
> 
> 本文由 [HCTT 翻译团队](https://github.com/hust-open-atom-club/TranslateProject)原创翻译，[华中科技大学开放原子开源俱乐部](https://github.com/hust-open-atom-club)荣誉推出。
