### ISSUE TITLE
脚本实现超链接转换

### ISSUE THREAD

**Issue by Earlystarry** [hust-open-atom-club/TranslateProject#9]
写一个脚本，能将文章原文内的超链接转换成[1], [2]，[3]形式，点击[1],[2],[3]就可以跳转到相应页面（而非点击原来的文字）。如下图所示。
![6f83f6dd_12849357](https://github.com/hust-open-atom-club/TranslateProject/assets/144318232/8d70df74-f5c4-4deb-a5ab-fbf43b89e004)

同时在文章结尾，形成一系列参考链接（如下图）。
![5c410bd0_12849357](https://github.com/hust-open-atom-club/TranslateProject/assets/144318232/d6f537f3-a40d-4e11-86cc-ca6158855f48)

**Comment by mudongliang** [comment]
已找到非常好用的公众号使用工具
